#!/usr/bin/env python3

import subprocess
import os
from typing import List

shutdown_icon = ""
reboot_icon = ""
sleep_icon = "󰤄"
lock_icon = ""
logout_icon = "󰗽"
yes_icon = ""
no_icon = ""

CONFIG_DIR = os.environ.get("XDG_CONFIG_HOME", "")
LOCKSCREEN_WALLPAPER = f"~/src/nixos/dotfiles/wall/ascii01.png"


def get_uptime() -> str:
    result = subprocess.run(["uptime"], capture_output=True, text=True).stdout.strip()
    
    if " up " in result:
        uptime_part = result.split(" up ")[1]
        uptime_str = uptime_part.split(",")[0]
        return uptime_str.strip()
    return result

#def get_uptime() -> str:
#    result = subprocess.run(["uptime", "-p"], capture_output=True, text=True)
#    return result.stdout.strip().replace("up ", "")

def main_menu() -> str:
    options: List[str] = [
        lock_icon,
        logout_icon,
        sleep_icon,
        shutdown_icon,
        reboot_icon,
    ]
    menu: str = "\n".join([f"{item}" for item in options])
    uptime = get_uptime()
    result = subprocess.run(
        [
            "rofi",
            "-dmenu",
            "-p",
            f"Uptime: {uptime}",
            "-mesg",
            f"Uptime: {uptime}",
            "-theme",
            f"~/.config/rofi/common.rasi",
        ],
        input=menu,
        capture_output=True,
        text=True,
    ).stdout.strip()
    return result.split("\n")[0]


def confirm() -> bool:
    options = [yes_icon, no_icon]
    menu: str = "\n".join([f"{item}" for item in options])
    result = subprocess.run(
        [
            "rofi",
            "-theme",
            f"~/.config/rofi/common.rasi",
            "-theme-str",
            "listview {columns: 2; lines: 1;}",
            "-dmenu",
            "-p",
            "Confirmation",
            "-mesg",
            "Confirm?",
        ],
        input=menu,
        capture_output=True,
        text=True,
    ).stdout.strip()
    return result == yes_icon


def power():
    selected = main_menu()

    action_map = {
        lock_icon: ["swaylock", "-i", LOCKSCREEN_WALLPAPER],
        sleep_icon: [
            "bash",
            "-c",
            "swaylock -f -C ~/.config/swaylock/config & sleep 1; systemctl suspend"
        ],
        #sleep_icon: [os.path.expanduser("~/.config/qtile/scripts/sleep.sh")],
        shutdown_icon: ["sudo", "shutdown", "now"],
        reboot_icon: ["reboot"],
        logout_icon: [
            "niri", "msg", "action", "quit"
        ],
    }

    if selected == lock_icon:
        subprocess.run(action_map[lock_icon])

    elif action := action_map[selected]:
        if confirm():
            subprocess.run(action)


if __name__ == "__main__":
    power()
