#!/bin/bash

# README
# cp to /usr/local/bin
# Make sure it's excetutable with 'chmod +x ./<name>

echo -e "\e[1m-------------------------------------\e[0m"
echo -e "\e[1mCommitting changes to repository. ~~>\e[0m"
echo -e "\e[1m-------------------------------------\e[0m"

git add .

git status
#git diff --staged

read -p "Commit message: " msg
[ -z "$msg" ] && { echo "Empty message"; exit 1; }

read -p "Commit and push? (y/N): " confirm
[[ "$confirm" != "y" ]] && exit 1

git commit -m "$msg"
git push
